
package SchoolGame;

import javax.swing.*;
import java.awt.*;

public class GameStart extends javax.swing.JFrame {

    
    
    ImageIcon image_ant = new ImageIcon("ant.jpg");
    ImageIcon image_bat = new ImageIcon("bat.jpg");
    ImageIcon image_cat = new ImageIcon("cat.jpg");
    ImageIcon image_cow = new ImageIcon("cow.jpg");
    ImageIcon image_fish = new ImageIcon("fish.jpg");
    ImageIcon image_fox = new ImageIcon("fox.jpg");
    ImageIcon image_gorilla = new ImageIcon("gorilla.jpg");
    ImageIcon image_giraffe = new ImageIcon("giraffe.jpg");
    ImageIcon image_toad = new ImageIcon("toad.jpg");
    ImageIcon image_dog = new ImageIcon("dog.jpg");
    
    
    
  
    
    public GameStart() {
        initComponents();
        this.setLocationRelativeTo(null);
        guessLabel.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batBtn = new javax.swing.JButton();
        catBtn = new javax.swing.JButton();
        fishBtn = new javax.swing.JButton();
        antBtn = new javax.swing.JButton();
        cowBtn = new javax.swing.JButton();
        toadBtn = new javax.swing.JButton();
        dogBtn = new javax.swing.JButton();
        giraffeBtn = new javax.swing.JButton();
        foxBtn = new javax.swing.JButton();
        gorillaBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        guessLabel = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showResult = new javax.swing.JTextArea();
        next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        batBtn.setText("Bat");
        batBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        batBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batBtnActionPerformed(evt);
            }
        });
        getContentPane().add(batBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 378, 71, 37));

        catBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        catBtn.setText("Cat");
        catBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catBtnActionPerformed(evt);
            }
        });
        getContentPane().add(catBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 378, 71, 37));

        fishBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fishBtn.setText("Fish");
        fishBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fishBtnActionPerformed(evt);
            }
        });
        getContentPane().add(fishBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 378, 71, 37));

        antBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        antBtn.setText("Ant");
        antBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        antBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antBtnActionPerformed(evt);
            }
        });
        getContentPane().add(antBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 378, 71, 37));

        cowBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cowBtn.setText("Cow");
        cowBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cowBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 378, 71, 37));

        toadBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toadBtn.setText("Toad");
        toadBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toadBtnActionPerformed(evt);
            }
        });
        getContentPane().add(toadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 453, 71, 35));

        dogBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dogBtn.setText("Dog");
        dogBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dogBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 453, 71, 35));

        giraffeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        giraffeBtn.setText("Giraffe");
        giraffeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giraffeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giraffeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(giraffeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 453, -1, 35));

        foxBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        foxBtn.setText("Fox");
        foxBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        foxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foxBtnActionPerformed(evt);
            }
        });
        getContentPane().add(foxBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 453, 71, 35));

        gorillaBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gorillaBtn.setText("Gorilla");
        gorillaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gorillaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gorillaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(gorillaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 453, 71, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Learn with image");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 13, 231, 50));

        guessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guessLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(guessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 423, 240));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 81, 58));

        showResult.setColumns(20);
        showResult.setRows(5);
        jScrollPane1.setViewportView(showResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, 263));

        next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 81, 55));

        jLabel3.setText("After learning vocabularies");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        jLabel4.setText("with image, let's start");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("QUIZ!!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void antBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antBtnActionPerformed
       guessLabel.setIcon(image_ant);
       showResult.append("Ants are found almost everywhere\n on the planet. Most species live\n in soil, leaf litter, or decaying\n plants.");
    }//GEN-LAST:event_antBtnActionPerformed

    private void batBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batBtnActionPerformed
       guessLabel.setIcon(image_bat);
       showResult.setText("Bats can be found in almost\nevery type of habitat. They live in deserts,\nwoodlands, suburban communities,\ncaves, and cities.");                                      
    }//GEN-LAST:event_batBtnActionPerformed

    private void catBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catBtnActionPerformed
       guessLabel.setIcon(image_cat);
       showResult.setText("Cat is found almost everywhere\n on the planet. Felis catus is the only \n domesticated species in the family.");
    }//GEN-LAST:event_catBtnActionPerformed

    private void cowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cowBtnActionPerformed
       guessLabel.setIcon(image_cow);
       showResult.setText("Cow is the most common farm\n animals around the world. They are a \nlarge mammals and have \nfour-chambered stomach.");
    }//GEN-LAST:event_cowBtnActionPerformed

    private void fishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fishBtnActionPerformed
       guessLabel.setIcon(image_fish);
       showResult.setText("Fish are aquatic animals that have gill \nto breath underwater. They have no legs\n but a fin.");
    }//GEN-LAST:event_fishBtnActionPerformed

    private void giraffeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giraffeBtnActionPerformed
       guessLabel.setIcon(image_giraffe);
       showResult.setText("Giraffe is a tall African mammal and the \ntallest of all land animals. They have \nlong necks and legs.");
    }//GEN-LAST:event_giraffeBtnActionPerformed

    private void toadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toadBtnActionPerformed
       guessLabel.setIcon(image_toad);
       showResult.setText("Toad is a common name for certain frogs \nthat have dry leathery skin,\n short legs and large bumps.");
    }//GEN-LAST:event_toadBtnActionPerformed

    private void foxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foxBtnActionPerformed
       guessLabel.setIcon(image_fox);
       showResult.append("Fox is small to medium-sized \nomnivorous mammal. They are closely \nrelated to domestic dogs and wolves.");
    }//GEN-LAST:event_foxBtnActionPerformed

    private void gorillaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gorillaBtnActionPerformed
       guessLabel.setIcon(image_gorilla);
       showResult.append("Gorilla is a herbivorous mammal. \nThey are a large black-coloured ape \nwith broad shoulders.");
    }//GEN-LAST:event_gorillaBtnActionPerformed

    private void dogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogBtnActionPerformed
       guessLabel.setIcon(image_dog);
       showResult.setText("Dog is a common pet. They have many \ndifferent species according to their size, \n shape and their furs.");
    }//GEN-LAST:event_dogBtnActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        Quiz quiz = new Quiz();
        quiz.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton antBtn;
    private javax.swing.JButton batBtn;
    private javax.swing.JButton catBtn;
    private javax.swing.JButton cowBtn;
    private javax.swing.JButton dogBtn;
    private javax.swing.JButton exit;
    private javax.swing.JButton fishBtn;
    private javax.swing.JButton foxBtn;
    private javax.swing.JButton giraffeBtn;
    private javax.swing.JButton gorillaBtn;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next;
    private javax.swing.JTextArea showResult;
    private javax.swing.JButton toadBtn;
    // End of variables declaration//GEN-END:variables
}
